# Generated by Django 5.0.4 on 2024-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patname', models.CharField(max_length=100)),
                ('patemail', models.EmailField(blank=True, max_length=254, unique=True)),
                ('patage', models.IntegerField(max_length=10)),
                ('patdisease', models.CharField(max_length=100)),
            ],
        ),
    ]
