# Generated by Django 5.0.4 on 2024-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patage',
            field=models.IntegerField(),
        ),
    ]
