# Generated by Django 5.0.4 on 2024-04-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_project', '0002_alter_patient_patage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patage',
        ),
    ]
