# Generated by Django 5.0.4 on 2024-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_project', '0003_remove_patient_patage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patage',
            field=models.IntegerField(default=0),
        ),
    ]
